import React, { Component } from 'react';
import './Privacidad.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';


class Privacidad extends Component {
    render() {
       return (
           <div>
               <Navbar />
            <div className="container pt-5">
                <h1 class="ion-article-title">Aviso de Privacidad Integral</h1>
							<p className="justify"><span className="stylings"> </span></p>
                            <p className="justify"><span className="stylings"> I. IDENTIDAD Y DOMICILIO DEL RESPONSABLE.</span></p>
                            <p className="justify"><span className="stylings">El responsable del tratamiento y protección de sus Datos Personales es Educación Magisterial México S.A.S. con domicilio en Miguel Lerdo de Tejada 325, Interior 104. Colonia Tezozomoc, Delegación Azcapotzalco, Ciudad de México CP 02459., en cumplimiento a la Ley Federal de Protección de Datos Personales en Posesión de Particulares, su Reglamento, así como los Lineamientos del Aviso de Privacidad publicados en el Diario Oficial de la Federación el 17 de enero de 2013, se hace de su conocimiento el presente Aviso de Privacidad. </span></p>
                            <p className="justify"><span className="stylings">Asimismo, al proporcionar tus Datos Personales a Educación Magisterial México S.A.S. a través de la página de internet www.lionsfield.mx, directamente en el domicilio, o por cualquier otro medio ya sea para pedir informes, inscribirse a algún curso de inglés, solicitar aplicación de exámenes o para cualquier otro fin mediante el cual sea necesario recabar información personal, tu aceptas el tratamiento de sus Datos Personales de la forma que se explica en el presente Aviso de Privacidad Integral. En caso contrario, se te recomienda no utilizar la página de internet y no proporcionar tus Datos Personales a Educación Magisterial México S.A.S. por ningún medio y para ningún fin. </span></p>
                            <p className="justify"><span className="stylings"> II. DATOS OBTENIDOS.</span></p>
                            <p className="justify"><span className="stylings">Para las finalidades mencionadas en este Aviso de Privacidad Integral, Educación Magisterial México S.A.S. podría solicitar y recabar de ti alguno de los siguientes datos “Datos Personales”:</span></p>
                            <p className="justify"><span className="stylings">1. En el caso de empleados o candidatos: </span></p>
                            <p className="justify">• <span className="stylings">Nombre completo.</span></p>
                            <p className="justify">• <span className="stylings">Fecha y lugar de nacimiento.</span></p>
                            <p className="justify">• <span className="stylings">Género &lpar;sexo&rpar;</span></p>
                            <p className="justify">• <span className="stylings">Estado civil.</span></p>
                            <p className="justify">• <span className="stylings">Domicilio.</span></p>
                            <p className="justify">• <span className="stylings">Correo electrónico.</span></p>
                            <p className="justify">• <span className="stylings">Número telefónico de casa y celular.</span></p>
                            <p className="justify">• <span className="stylings">Número de cuenta bancaria para pago de nómina. </span></p>
                            <p className="justify">• <span className="stylings">Registro Federal de Contribuyentes &lpar;RFC&rpar;.</span></p>
                            <p className="justify">• <span className="stylings">Clave Única de Registro de Población &lpar;CURP&rpar;.</span></p>
                            <p className="justify">• <span className="stylings">Número de Seguridad Social.</span></p>
                            <p className="justify">• <span className="stylings">Número de Registro Patronal.</span></p>
                            <p className="justify">• <span className="stylings">Nombre de su padre y madre.</span></p>
                            <p className="justify">• <span className="stylings">Nombre de su esposo o esposa y nombre de sus hijos y en su caso información de dependientes económicos.</span></p>
                            <p className="justify">• <span className="stylings">Formación profesional y académica.</span></p>
                            <p className="justify">• <span className="stylings">Experiencia laboral.</span></p>
                            <p className="justify"><span className="stylings">2. En el caso de clientes: </span></p>
                            <p className="justify">• <span className="stylings">Nombre completo.</span></p>
                            <p className="justify">• <span className="stylings">Fecha de nacimiento.</span></p>
                            <p className="justify">• <span className="stylings">Género &lpar;sexo&rpar;.</span></p>
                            <p className="justify">• <span className="stylings">Estado civil.</span></p>
                            <p className="justify">• <span className="stylings">Domicilio.</span></p>
                            <p className="justify">• <span className="stylings">Correo electrónico.</span></p>
                            <p className="justify">• <span className="stylings">Número telefónico de casa y celular.</span></p>
                            <p className="justify">• <span className="stylings">Clave Única de Registro de Población &lpar;CURP&rpar;.</span></p>
                            <p className="justify">• <span className="stylings">Registro Federal de Contribuyentes &lpar;RFC&rpar;.</span></p>
                            <p className="justify">• <span className="stylings">Ocupación.</span></p>
                            <p className="justify">• <span className="stylings">Lugar de trabajo y datos de la empresa.</span></p>
                            <p className="justify">• <span className="stylings">Datos de las personas a quien contactar en casos de emergencia; y, en caso de menores de edad, la misma información mencionada en los puntos anteriores de sus padres o tutor.</span></p>
                            <p className="justify"><span className="stylings">3. En el caso de proveedores: </span></p>
                            <p className="justify">• <span className="stylings">Nombre completo.</span></p>
                            <p className="justify">• <span className="stylings">Domicilio.</span></p>
                            <p className="justify">• <span className="stylings">Dirección de correo electrónico.</span></p>
                            <p className="justify">• <span className="stylings">Número telefónico de trabajo. </span></p>
                            <p className="justify">• <span className="stylings">Número de cuenta bancario para el pago.</span></p>
                            <p className="justify">• <span className="stylings">Registro Federal de Contribuyentes &lpar;RFC&rpar;.</span></p>
                            <p className="justify">• <span className="stylings">Clave Única de Registro de Población &lpar;CURP&rpar;.</span></p>
                            <p className="justify"><span className="stylings">En caso de que tengas acceso a este Aviso de Privacidad Integral mediante nuestro sitio web, el mismo puede ser visitado y navegado sin necesidad de proporcionar Datos Personales, con excepción del servicio del módulos denominado “Contacto”, utilizado para recibir información, inscribirte o evaluar tu nivel del inglés.</span></p>
                            <p className="justify"><span className="stylings">Nosotros no recabamos datos sensibles en nuestro sitio web.</span></p>
                            <p className="justify"><span className="stylings"> III. FINALIDADES.</span></p>
                            <p className="justify"><span className="stylings">Los datos personales obtenidos serán utilizados para las siguientes finalidades:</span></p>
                            <p className="justify"><span className="stylings">Finalidades Primarias:</span></p>
                            <p className="justify"><span className="stylings">En el caso de empleados o candidatos: Solicitud de datos como parte integral del procedimiento interno de contratación; realizar el pago de la nómina; mantener actualizados los datos; intercambio de información con Secretaria de Hacienda y Crédito Público &lpar;“SHCP”&rpar; para el cumplimiento de normatividad fiscal; intercambio de información con el Instituto Mexicano del Seguro Social &lpar;“IMSS”&rpar;, el Instituto del Fondo Nacional de la Vivienda para los Trabajadores &lpar;“INFONAVIT”&rpar; y Administradoras de Fondos para el Retiro &lpar;“AFORES”&rpar; para el cumplimiento de normatividad de seguridad social; intercambio de información con terceros para tramitar y otorgar beneficios.</span></p>
                            <p className="justify"><span className="stylings">En el caso de clientes: Para la Prestación de Servicios y proveer a usted los correspondientes servicios y productos que ha solicitado de Educación Magisterial México S.A.S., ya sea para la Enseñanza del Idioma Inglés, Talleres Conversacionales, Cursos Regulares por Negocios por Nivel, Cursos Propedéuticos, Impartición de Seminarios, Servicio de Traducciones y Preparación para Exámenes de Certificación del Idioma Inglés, así como para dar cumplimiento con los acuerdos y/o contratos celebrados con Educación Magisterial México S.A.S., con el objeto de identificarle, asegurar la funcionalidad y la calidad de los servicios, enviar los resultados de sus evaluaciones cuando se haya solicitado una certificación internacional del inglés o ante la Secretaria de Educación Pública. Asimismo, Educación Magisterial México S.A.S. puede utilizar sus Datos Personales para informarle y hacer de su conocimiento nuevos productos y servicios, promociones, descuentos o cualquier información que pudiera ser de su interés para el aprendizaje del idioma inglés. Expedir los comprobantes fiscales correspondientes por el pago de los servicios y productos adquiridos de Educación Magisterial México S.A.S.. Intercambio de información con Secretaria de Hacienda y Crédito Público para el cumplimiento de normatividad fiscal.</span></p>
                            <p className="justify"><span className="stylings">En el caso de proveedores: Realizar el pago de las cuentas pendientes a cargo de Educación Magisterial México S.A.S.; intercambio de información con Secretaria de Hacienda y Crédito Público para el cumplimiento de normatividad fiscal.</span></p>
                            <p className="justify"><span className="stylings">Finalidades Secundarias:</span></p>
                            <p className="justify"><span className="stylings">Educación Magisterial México S.A.S. podrá utilizar su información con fines:</span></p>
                            <p className="justify"><span className="stylings">a&rpar; Estadísticos.</span></p>
                            <p className="justify"><span className="stylings">b&rpar; Comunicación, recomendaciones y mostrarle el contenido de nuestros servicios.</span></p>
                            <p className="justify"><span className="stylings">c&rpar; Invitarlo a participar en juegos y sorteos organizados por Educación Magisterial México S.A.S. o por cualquier tercero.</span></p>                            
                            <p className="justify"><span className="stylings">d&rpar; Promociones y Descuentos &lpar;Mercadotecnia y Publicidad&rpar;.</span></p>
                            <p className="justify"><span className="stylings">e&rpar; Compartir su nombre y datos de contacto a las empresas que pertenecen al mismo grupo de inversión, a sociedades filiales, subsidiarias y controladoras para fines informativos y de publicidad.</span></p>
                            <p className="justify"><span className="stylings"> IV. NEGATIVA AL TRATAMIENTO PARA FINALIDADES SECUNDARIAS</span></p>
                            <p className="justify"><span className="stylings">Si deseas que tus datos personales NO se utilicen desde este momento para todas o cualquiera de las finalidades secundarias establecidas en el presente Aviso de Privacidad Integral, envíanos un correo electrónico a: atenion@lionsfield.com indicándonos lo siguiente</span></p>
                            <p className="justify"><span className="stylings">No consiento que mis datos personales se utilicen para las siguientes Finalidades secundarias:</span></p>
                            <p className="justify"><span className="stylings">a&rpar; Estadísticos.</span></p>
                            <p className="justify"><span className="stylings">b&rpar; Comunicación, recomendaciones y mostrarle el contenido de nuestros servicios.</span></p>
                            <p className="justify"><span className="stylings">c&rpar; Invitarlo a participar en juegos y sorteos organizados por Educación Magisterial México S.A.S. o por cualquier tercero.</span></p>
                            <p className="justify"><span className="stylings">d&rpar; Promociones y Descuentos &lpar;Mercadotecnia y Publicidad&rpar;.</span></p>
                            <p className="justify"><span className="stylings">e&rpar; Compartir su nombre y datos de contacto a las empresas que pertenecen al mismo grupo de inversión, a sociedades filiales, subsidiarias y controladoras para fines informativos y de publicidad.</span></p>
                            <p className="justify"><span className="stylings">Por favor indíquenos solo las finalidades a las cuales nos niegas el tratamiento de tus datos personales, nosotros atenderemos tu petición y dejaremos de tratar tus datos para las finalidades secundarias que tú nos indiques. Manifestar tu negativa al tratamiento de tus datos personales para finalidades secundarias no podrá ser motivo para dejar de brindarte nuestros servicios.</span></p>
                            <p className="justify"><span className="stylings"> V. TRANSFERENCIAS</span></p>
                            <p className="justify"><span className="stylings">Educación Magisterial México S.A.S. no vende, alquila o de otra forma divulga sus Datos Personales a terceros excepto cuando: a&rpar; se cuente con su autorización y/o aprobación y b&rpar; en caso de que Educación Magisterial México S.A.S. realice una operación de venta, compra, fusión o escisión entre empresas filiales y/o subsidiarias, o de cualquier forma de reorganización de empresas, pudiendo ser necesaria la divulgación de Datos Personales a prospectos o compradores propiamente dichos y a los asesores de éstos. </span></p>
                            <p className="justify"><span className="stylings"> VI. DERECHOS ARCO</span></p>
                            <p className="justify"><span className="stylings">Tú tienes derecho a conocer qué datos personales tenemos de ti, para qué los utilizamos y las condiciones del uso que les damos &lpar;Acceso&rpar;. Asimismo, es tu derecho solicitar la corrección de tu información personal en caso de que esté desactualizada, sea inexacta o incompleta &lpar;Rectificación&rpar;; que eliminemos tu información, de nuestros registros o bases de datos cuando consideres que la misma no está siendo utilizada conforme a los principios, deberes y obligaciones previstas en la normativa &lpar;Cancelación&rpar;; así como puedes oponerte al uso de tus datos personales para fines específicos &lpar;Oposición&rpar;. Estos derechos se conocen como derechos ARCO.</span></p>
                            <p className="justify"><span className="stylings">Tú puedes ejercer los derechos anteriormente mencionados a través del formulario “Solicitud para Atención a los Requerimientos ARCO” para lo anterior deberás enviar un correo electrónico a la dirección: atencion@lionsfield.com solicitando el formulario correspondiente y seguir el procedimiento que será enviado junto con tu solicitud o bien si lo deseas puedes acudir a nuestras oficinas en Liverpool 172 Piso 3, Colonia Juárez, México, Distrito Federal, Código Postal 06600, así también puedes ponerte en contacto con nuestro Departamento de Privacidad al teléfono &lpar;55&rpar; 1012 6649 que dará trámite a las solicitudes para el ejercicio de estos derechos, y atenderá cualquier duda que pudieras tener respecto al tratamiento de su información. </span></p>
                            <p className="justify"><span className="stylings"> VII. REVOCACIÓN DE CONSENTIMIENTO.</span></p>
                            <p className="justify"><span className="stylings">Tú puedes revocar el consentimiento que nos hayas otorgado para el tratamiento de tus datos personales. Sin embargo, es importante que tengas en cuenta que no en todos los casos podremos atender tu solicitud o concluir el uso de tus datos personales de forma inmediata debido, a que es posible que por alguna obligación legal requiramos seguir tratando tus datos personales. Asimismo debes considerar que para ciertos fines, la revocación de tu consentimiento implicará que no podamos seguir brindándote el servicio que nos solicitas.</span></p>
                            <p className="justify"><span className="stylings">Para solicitar la revocación de tu consentimiento deberás enviar un correo a la siguiente dirección atencion@lionsfield.com solicitando el “Formato del Revocación del Consentimiento” y seguir el procedimiento que será enviado junto con tu solicitud. Nosotros analizaremos tu caso y te enviaremos respuesta a tu solicitud de acuerdo a nuestro procedimiento establecido. </span></p>
                            <p className="justify"><span className="stylings"> VIII. LIMITAR EL USO O DIVULGACIÓN DE LOS DATOS PERSONALES</span></p>
                            <p className="justify"><span className="stylings">Si deseas limitar el uso o divulgación de los datos personales que nos ha otorgado con fines de publicidad y/o mercadotecnia, envíenos un correo a la dirección: atencion@lionsfield.com, o puedes darte de baja automáticamente desde nuestros mismos correos que te serán enviados haciendo clic en la parte “remover suscripción” o podrá dar aviso a los teléfonos de Educación Magisterial México S.A.S. &lpar;55&rpar; 1012 6649, solicitando que usted sea excluido para que su información personal no sea tratada para fines de mercadotecnia, publicitario o de prospección comercial por nuestra parte, o bien, su inscripción en el Registro Público para Evitar Publicidad, que ésta a cargo de la Procuraduría Federal del Consumidor, con la finalidad de que sus Datos Personales y/o Datos Personales Sensibles no sean utilizados para recibir publicidad o promociones de empresas de bienes o servicios. Para mayor información sobre éste Registro usted puede consultar el portal de Internet de la PROFECO, o bien ponerse en contacto directo con ésta. Nos comprometemos a incluir tu información a un Listado de Exclusión para suspender toda actividad relacionada con el ofrecimiento de servicios &lpar;publicidad y/o mercadotecnia&rpar; que pudiera recaer en actos de molestia respecto del uso de tu información. </span></p>
                            <p className="justify"><span className="stylings"> IX. EL USO DE TECNOLOGÍAS DE RASTREO EN NUESTRO PORTAL DE INTERNET</span></p>
                            <p className="justify"><span className="stylings">Te informamos que en nuestra página de Internet utilizamos cookies, web beacons y otras tecnologías a través de las cuales es posible monitorear tu comportamiento como usuario de Internet, para brindarte un mejor servicio y experiencia al navegar en nuestra página, así como ofrecerte nuevos productos y servicios basados en tus preferencias.</span></p>
                            <p className="justify"><span className="stylings">Los datos personales que obtenemos de estas tecnologías de rastreo son los siguientes: Navegador que utilizas, nombre del servidor, dirección IP, fecha horario y tiempo de navegación en internet y en nuestro sitio, secciones consultadas, y páginas de Internet accedidas cuando estas en nuestro sitio web.</span></p>
                            <p className="justify"><span className="stylings">Estas tecnologías podrán deshabilitarse siguiendo los siguientes pasos: 1. Acceder a nuestra página de Internet, 2. Dar clic en la subsección “Cookies” de su navegador; 3. Dar clic en la leyenda de activar el mecanismo de deshabilitación de cookies.</span></p>
                            <p className="justify"><span className="stylings"> X. DEPARTAMENTO DE PRIVACIDAD DE DATOS PERSONALES</span></p>
                            <p className="justify"><span className="stylings">Si tienes preguntas sobre este Aviso de Privacidad Integral para Sitio Web, o del tratamiento que les estamos dando a tus Datos Personales, ponte en contacto con nuestro Departamento de Privacidad de datos personales, donde con gusto te atenderemos:</span></p>
                            <p className="justify"><span className="stylings">Domicilio: Liverpool 172 Piso 3, Colonia Juárez, México, Distrito Federal, C. P. 06600.</span></p>
                            <p className="justify"><span className="stylings">Correo electrónico: atencion@lionsfield.com </span></p>
                            <p className="justify"><span className="stylings">Teléfono: &lpar;55&rpar; 1012 6649</span></p>
                            <p className="justify"><span className="stylings"> XI. ACTUALIZACIÓN DEL AVISO DE PRIVACIDAD</span></p>
                            <p className="justify"><span className="stylings">Este Aviso de Privacidad puede sufrir modificaciones, cambios o actualizaciones derivadas de nuevos requerimientos legales, de nuestras propias necesidades, por el mejoramiento a prácticas internas, cambio en el modelo de negocio o por cualquier otra causa.</span></p>
                            <p className="justify"><span className="stylings">Por lo anterior, hacemos de su conocimiento que en caso de modificación del presente aviso, Educación Magisterial México S.A.S. publicará dicha modificación en su página de internet www.lionsfield.mx, en caso de que en el plazo de 5 &lpar;cinco&rpar; días usted no ejerza cualesquiera de los derechos ARCO a que tiene derecho, se entenderá que consintió los cambios realizados a dicho Aviso de Privacidad.</span></p>
                            <p className="justify"><span className="stylings"> XII. CONSENTIMIENTO</span></p>
                            <p className="justify"><span className="stylings">Educación Magisterial México S.A.S. se compromete a que los Datos Personales que por cualquier medio se recaban, serán tratados bajo las más estrictas medidas de seguridad que garanticen su confidencialidad, por lo que usted consiente su tratamiento por parte de Educación Magisterial México S.A.S. en los términos que se consignan en este Aviso, salvo que medie una petición expresa de oposición al tratamiento de sus Datos Personales de acuerdo al procedimiento establecido en el presente Aviso.</span></p>
                            <p className="justify"><span className="stylings">Fecha de actualización: febrero de 2016 </span></p>
            </div>
            <Footer />
        </div>
       );
    }
}

export default Privacidad